# Generated by Django 5.1.4 on 2026-03-16 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        ('vendor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorProductMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('primary_mapping', models.BooleanField(default=False)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_vendor_mappings', to='product.product')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_product_mappings', to='vendor.vendor')),
            ],
            options={
                'verbose_name': 'Vendor–Product Mapping',
                'verbose_name_plural': 'Vendor–Product Mappings',
                'db_table': 'vendor_product_mapping',
                'ordering': ['-created_at'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('parent', 'child'), name='uniq_vendor_product_pair'), models.UniqueConstraint(condition=models.Q(('primary_mapping', True)), fields=('parent',), name='uniq_primary_vendor_product_per_parent')],
            },
        ),
    ]
