# Generated by Django 5.1.4 on 2026-03-16 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCourseMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('primary_mapping', models.BooleanField(default=False)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_product_mappings', to='course.course')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_course_mappings', to='product.product')),
            ],
            options={
                'verbose_name': 'Product–Course Mapping',
                'verbose_name_plural': 'Product–Course Mappings',
                'db_table': 'product_course_mapping',
                'ordering': ['-created_at'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('parent', 'child'), name='uniq_product_course_pair'), models.UniqueConstraint(condition=models.Q(('primary_mapping', True)), fields=('parent',), name='uniq_primary_product_course_per_parent')],
            },
        ),
    ]
